# Generated by Django 3.1.13 on 2024-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
