# Generated by Django 3.1.13 on 2024-01-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialtransfer',
            name='date_of_transfer',
            field=models.DateField(auto_now_add=True),
        ),
    ]
